[build]
  command = "npm ci --prefer-offline --no-audit && npm run build"
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  ESLINT_NO_DEV_ERRORS = "true"  # Prevents ESLint warnings from failing build
  NODE_ENV = "development"  # Ensures devDependencies install

[context.production]
  command = "npm ci --prefer-offline --no-audit && npm run build"
  [context.production.environment]
    NODE_ENV = "production"  # Only set production after install

# ... rest of your config remains the same ...
