[build]
  command = "npm run build"
  publish = "hnm-ministry/dist"
  functions = "hnm-ministry/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"

# Remove ALL other sections temporarily
