[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "dist"
  functions = "functions"
  base = "hnm-ministry"  # Add this line since your files are in the hnm-ministry subdirectory

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # Environment variables (reference Netlify UI secrets)
  VITE_STRIPE_KEY = "@stripe_key"
  VITE_FORMPREE_ID = "@formspree_id"
  VITE_API_BASE_URL = "@api_url"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://js.stripe.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https://*.stripe.com;
      connect-src 'self' https://api.stripe.com;
      frame-src https://js.stripe.com;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
