[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", NODE_ENV = "development" }

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
