[build]
  # Let Netlify handle all dependency management
  command = "npm install --force && npm run build"
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Force clean dependency installation
  NPM_FLAGS = "--legacy-peer-deps --force"
  # Build optimization
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # Vite-specific environment variables
  VITE_STRIPE_KEY = "@stripe_publishable_key"
  VITE_FORMPREE_ID = "@formspree_id"
  VITE_API_BASE_URL = "https://api.hnm-ministry.org"

[context.production]
  environment = { 
    VITE_API_BASE_URL = "https://api.hnm-ministry.org",
    NODE_ENV = "production"
  }

[context.deploy-preview]
  environment = { 
    VITE_API_BASE_URL = "https://staging-api.hnm-ministry.org",
    NODE_ENV = "development"
  }

[dev]
  framework = "vite"
  targetPort = 5173
  autoLaunch = false

# Security headers (using your existing config)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
