# Let Netlify handle all dependency installation and building
  command = "npm install --force && npm run build"
  publish = "dist"            # Vite's default output folder
  functions = "functions"     # Serverless 

[build.environment]
  # Node.js environment
  NODE_VERSION = "22.15.0"         # Current LTS
  NPM_VERSION = "11.3.0"
  
  # Environment variables (set in Netlify UI)
  VITE_STRIPE_KEY = "@stripe_key"
  VITE_FORMPREE_ID = "@formspree_id"
  VITE_API_BASE_URL = "@api_url"

# Production-specific config
[context.production.environment]
  NODE_ENV = "production"

# Preview deployments (PRs)
[context.deploy-preview.environment]
  NODE_ENV = "development"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# API redirects to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200
  force = true
