[build]
  command = "npm ci && npm run build"  # Let Netlify handle everything
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "20"  # Just specify major version (Netlify will auto-select latest 20.x)
  NPM_VERSION = "auto"  # Let Netlify choose compatible npm
  ESLINT_NO_DEV_ERRORS = "true"  # Disable ESLint errors in build

# Production environment (optimized)
[context.production]
  command = "npm ci --prefer-offline && npm run build"
  [context.production.environment]
    NODE_ENV = "production"

# Simpler preview environments
[context.deploy-preview]
  command = "npm install && npm run build"
  
[context.branch-deploy]
  command = "npm install && npm run build"
