[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"  

[build.environment]
  NODE_VERSION = "20.13.1"  
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

  # Environment variables
  VITE_STRIPE_KEY = "$STRIPE_PUBLISHABLE_KEY"
  VITE_FORMPREE_ID = "$API_FORMSPREE_ID"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com; script-src 'self' 'unsafe-inline' https://js.stripe.com; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
