[build]
  command = "npm install --legacy-peer-deps --no-audit && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "development" # Required for devDependencies
