[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"  # Only include if using Netlify Functions
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

# Essential security headers for Vite/React
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' *.stripe.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: *.stripe.com;
      connect-src 'self' *.stripe.com *.googleapis.com;
      frame-src *.stripe.com;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"

# Critical for SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
