[build]
  command = "npm install && npm run build"  # First installs dependencies, then builds
  publish = "dist"
  functions = "netlify/functions"  # Only include if using Functions
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  # Ensure devDependencies (like Vite) are installed:
  NPM_FLAGS = "--production=false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
