[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"  # Remove if not using Functions
  edge_functions = "netlify/edge-functions"  # Remove if not using Edge Functions

[build.environment]
  # Stable versions that work with Vite 5
  NODE_VERSION = "20.13.1"  # LTS version known to work well with Vite
  NPM_VERSION = ""  # Let Netlify use default npm for Node version
  
  # Dependency installation settings
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  
  # Vite-specific optimizations
  VITE_STRIPE_KEY = "$STRIPE_PUBLISHABLE_KEY"

# Development context (optional)
[context.develop]
  NODE_ENV = "development"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com; script-src 'self' 'unsafe-inline' https://js.stripe.com; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
