[build]
  command = "npm ci && npm run build"  # Uses clean install for reliability
  publish = "dist"
  functions = "netlify/functions"     # Remove if not using Functions
  base = "."

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
  NODE_ENV = "production"
  # Critical for Vite installation:
  NPM_FLAGS = "--production=false"    # Ensures devDependencies are installed
  CI = "false"                       # Prevents CI-specific optimizations that may break builds

# Security headers (simplified)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com"
    X-Content-Type-Options = "nosniff"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
