[build]
  command = "npm ci --prefer-offline && npm install --legacy-peer-deps && npm run build && npm run optimize-assets"
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "20.5.0"  # Ensure Node.js version is 20.5.0
  NPM_VERSION = "10.9.2"  # Ensure npm version is 10.9.2
  VITE_APP_VERSION = "$npm_package_version"
  VITE_API_BASE_URL = "https://api.hnm.org"
  VITE_SENTRY_DSN = "https://your-dsn@sentry.io/your-project"
  VITE_STRIPE_PUBLISHABLE_KEY = "@stripe_publishable_key"
  VITE_MAGIC_PUB_KEY = "@magic_pub_key"
  VITE_APP_ENV = "production"

[context.production]
  command = "npm ci --prefer-offline && npm install --legacy-peer-deps && npm run build && npm run optimize-assets && npm run type-check"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "production"
    SENTRY_RELEASE = "$COMMIT_REF"
    SENTRY_ENVIRONMENT = "production"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    VITE_APP_ENV = "staging"
    VITE_API_BASE_URL = "https://staging.api.hnm.org"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_APP_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://js.stripe.com https://connect.facebook.net 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: blob: https://*.stripe.com https://*.facebook.com https://*.youtube.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src https://www.youtube.com https://www.facebook.com https://js.stripe.com;
      connect-src 'self' https://api.stripe.com https://bible-api.com https://api.hnm.org https://*.magic.link;
      media-src 'self' https://*.youtube.com;
      worker-src 'self' blob:;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = """
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(self https://js.stripe.com)
    """
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 3000
  autoLaunch = false
  command = "npm run dev"
  port = 3000

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["faunadb", "stripe"]

[[edge_functions]]
  path = "/edge-functions/hello"
  function = "hello"


