[build]
  command = "npm install --force && npm run build"
  publish = "dist"  # Adjusted for your subfolder structure
  functions = "hnm-ministry/functions"
  base = ""  # Critical for subdirectory projects

[build.environment]
  NODE_VERSION = "22.15.0"  # Recommended stable version
  NPM_VERSION = "10.9.2"
  NODE_ENV = "production"
  
  # Environment variables (reference Netlify UI secrets)
  VITE_STRIPE_KEY = "@stripe_key"
  VITE_FORMPREE_ID = "@formspree_id"
  VITE_API_BASE_URL = "@api_url"

# Required for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
