[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Add this to override default Netlify behavior

# For SPA routing - handle all client-side routes
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200
