[build]
  command = "cd hnm-ministry && npm install --legacy-peer-deps --force && npm run build"
  publish = "hnm-ministry/dist"
  functions = "hnm-ministry/functions"

[build.environment]
  NODE_VERSION = "20"  # More stable than v22
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps --force"  # Critical for resolution
  
  # Environment variables
  VITE_STRIPE_KEY = "@stripe_key"
  VITE_FORMPREE_ID = "@formspree_id"
  VITE_API_BASE_URL = "@api_url"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
