[build]
  command = "cd hnm-ministry && npm install --legacy-peer-deps --force && npm run build"
  publish = "hnm-ministry/dist"
  functions = "hnm-ministry/functions"

# Critical SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
