[build]
  command = "npm ci --prefer-offline && npm run build"
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "20"  # Uses latest Node 20.x automatically
  NPM_VERSION = "10"   # Uses latest npm 10.x (remove "auto")
  NODE_ENV = "development" # Allows devDependencies installation
  
  # Vite-specific
  VITE_APP_VERSION = "$npm_package_version"
  VITE_API_BASE_URL = "https://api.hnm.org"

[context.production]
  command = "npm ci --prefer-offline && npm run build"
  [context.production.environment]
    NODE_ENV = "production" # Now explicitly set AFTER initial install

[context.deploy-preview]
  command = "npm ci --prefer-offline && npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "default-src 'self'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173
  command = "npm run dev"
