[build]
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "18" # Stable LTS version
  NPM_VERSION = "9"
  NODE_ENV = "production"

# Netlify will automatically:
# 1. Run `npm install`
# 2. Run `npm run build` (from your package.json)
# No need for explicit build command

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
