[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", NODE_ENV = "production" } # Changed to production

[dev]
  command = "npm install && npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
