[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "functions"
  edge_functions = "edge-functions"  # Add this line for edge functions

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  VITE_STRIPE_KEY = "your_publishable_key_here"
  VITE_FORMPREE_ID = "your_formspree_id_here"

[[redirects]]
  from = "/api/donate"
  to = "/.netlify/functions/donate"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/src/index.html"
  status = 200

# Edge function declarations
[[edge_functions]]
  path = "/*"  # Applies to all routes
  function = "geo-redirect"  # Matches your geo-redirect.js filename

[dev]
  framework = "vite"
  targetPort = 5173
  autoLaunch = false
