[build]
  command = "npm install --production=false && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"
  
  # Environment variables (set in Netlify UI)
  VITE_STRIPE_KEY = "@stripe_publishable_key"
  VITE_FORMPREE_ID = "@formspree_id"
  VITE_API_BASE_URL = "@api_base_url"
  VITE_SENTRY_DSN = "@sentry_dsn"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https: *.stripe.com *.googleapis.com *.gstatic.com"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
