[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://js.stripe.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://*.stripe.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://api.stripe.com https://formspree.io;
      frame-src https://js.stripe.com;
    '''
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
