- name: Netlify Deploy
  env:
    STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
    FORMSPREE_FORM_ID: ${{ secrets.FORMSPREE_FORM_ID }}
  run: netlify deploy --prod
